# Generated by Django 5.2 on 2025-04-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('is_available', models.BooleanField(default=True)),
                ('is_spicy', models.BooleanField(default=False)),
            ],
        ),
    ]
